{{- if .Values.deploy.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus.name" . }}
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
type: Opaque
data:
  db.username: {{ .Values.deploy.secrets.db.username }}
{{- end }}